const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Button,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Platform,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Behaviors.solid,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Behaviors.Flash,
		C3.Behaviors.Bullet,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.time,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.ResetGlobals
	];
};
self.C3_JsPropNameTable = [
	{InicialWallpaper: 0},
	{BotãoStart: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{Plataforma: 0},
	{Senóide: 0},
	{Player: 0},
	{Girar: 0},
	{Moeda: 0},
	{Fantasma: 0},
	{Sólido: 0},
	{chão: 0},
	{Esmaecer: 0},
	{Explosão: 0},
	{explosão_fantasma: 0},
	{Âncora: 0},
	{Pontos: 0},
	{Áudio: 0},
	{Teclado: 0},
	{Fundo: 0},
	{MoedaM: 0},
	{Monstro: 0},
	{GameOverFundo: 0},
	{Piscar: 0},
	{Reiniciar: 0},
	{TutorialWallpaper: 0},
	{tutorial: 0},
	{ComoJogar: 0},
	{BotãoVoltar: 0},
	{vida: 0},
	{Projétil: 0},
	{perdaDeVida: 0},
	{MoedaG: 0},
	{explosão_monstro: 0},
	{Texto: 0},
	{velocidade_moeda: 0},
	{TempoSpawnMoeda: 0},
	{velocidade_fantasma: 0},
	{TempoSpawnFantasma: 0},
	{velocidade_monstro: 0},
	{TempoSpawnMonstro: 0},
	{vida_03: 0}
];

self.InstanceType = {
	InicialWallpaper: class extends self.ISpriteInstance {},
	BotãoStart: class extends self.IButtonInstance {},
	Player: class extends self.ISpriteInstance {},
	Moeda: class extends self.ISpriteInstance {},
	Fantasma: class extends self.ISpriteInstance {},
	chão: class extends self.ISpriteInstance {},
	Explosão: class extends self.ISpriteInstance {},
	explosão_fantasma: class extends self.ISpriteInstance {},
	Pontos: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	Fundo: class extends self.ISpriteInstance {},
	MoedaM: class extends self.ISpriteInstance {},
	Monstro: class extends self.ISpriteInstance {},
	GameOverFundo: class extends self.ISpriteInstance {},
	Reiniciar: class extends self.IButtonInstance {},
	TutorialWallpaper: class extends self.ISpriteInstance {},
	tutorial: class extends self.ITextInstance {},
	ComoJogar: class extends self.IButtonInstance {},
	BotãoVoltar: class extends self.IButtonInstance {},
	vida: class extends self.ITextInstance {},
	perdaDeVida: class extends self.ISpriteInstance {},
	MoedaG: class extends self.ISpriteInstance {},
	explosão_monstro: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {}
}